spring.application.name=sb1app
server.port= 8811


spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url = jdbc:mysql://localhost:3306/connection	
spring.datasource.password=Bharath@8184
spring.datasource.username=root

# Hibernate ddl auto (create, create-drop, validate, update)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
 